import type { Lesson } from '../types/lesson'

const lesson: Lesson = {
  id: 'healthcare-hospital',
  title: 'Healthcare and Hospital',
  level: 'B1',
  topic: 'Medical English',
  description: 'Learn healthcare vocabulary, practise should/could, and complete interactive hospital-themed tasks.',
  coverImage: '/assets/healthcare-hospital/hero.jpg',
  sections: [
    {
      id: 'hero',
      type: 'hero',
      title: 'Healthcare and Hospital',
      emoji: '🏥',
      level: 'B1',
      subtitle: 'Glossary, grammar, reading, speaking, and practical exercises about hospital situations.',
      imageSrc: '/assets/healthcare-hospital/hero.jpg',
      goals: [
        'Learn B1 hospital and healthcare vocabulary',
        'Use should for advice and could for polite requests and possibility',
        'Read and discuss a short medical story',
        'Practise key lesson vocabulary in interactive tasks',
      ],
      words: [
        'patient',
        'GP',
        'surgeon',
        'nurse',
        'radiologist',
        'ER',
        'ICU',
        'pharmacy',
        'blood test',
        'X-ray',
        'prescription',
        'antibiotics',
        'painkiller',
        'dosage',
        'side effects',
        'dizzy',
        'fever',
        'infection',
      ],
      functionalLanguage: [
        'You should check the dosage carefully.',
        'You should not ignore a high fever.',
        'Could you show me where the pharmacy is?',
        'The diagnosis could be wrong.',
        'Could I have a painkiller, please?',
      ],
    },
    {
      id: 'glossary-categories',
      type: 'vocabulary-categories',
      title: 'Healthcare glossary',
      emoji: '📚',
      categories: [
        {
          label: 'People',
          color: 'blue',
          words: [
            { word: 'patient', definition: 'a person receiving medical treatment' },
            { word: 'GP', definition: 'a family doctor for common illnesses' },
            { word: 'specialist', definition: 'a doctor for a specific area of medicine' },
            { word: 'surgeon', definition: 'a doctor who performs operations' },
            { word: 'nurse', definition: 'a professional who cares for patients' },
            { word: 'radiologist', definition: 'a doctor who reads X-rays and scans' },
          ],
        },
        {
          label: 'Places',
          color: 'green',
          words: [
            { word: 'ER', definition: 'emergency room for urgent cases' },
            { word: 'ward', definition: 'hospital room with several patient beds' },
            { word: 'OR', definition: 'operating room for surgery' },
            { word: 'ICU', definition: 'intensive care for very ill patients' },
            { word: 'pharmacy', definition: 'place where medicine is given or sold' },
            { word: 'waiting room', definition: 'area where patients wait for appointments' },
          ],
        },
        {
          label: 'Procedures and equipment',
          color: 'orange',
          words: [
            { word: 'examination', definition: 'doctor checks the body to find problems' },
            { word: 'check-up', definition: 'routine medical examination' },
            { word: 'surgery', definition: 'medical operation on the body' },
            { word: 'X-ray', definition: 'image of inside the body, often for bones' },
            { word: 'blood test', definition: 'sample of blood to check health' },
            { word: 'injection', definition: 'medicine given with a needle' },
            { word: 'stretcher', definition: 'mobile bed for carrying patients' },
          ],
        },
        {
          label: 'Treatment and symptoms',
          color: 'purple',
          words: [
            { word: 'prescription', definition: 'doctor note for specific medicine' },
            { word: 'antibiotics', definition: 'medicine that treats bacterial infections' },
            { word: 'painkiller', definition: 'medicine that reduces pain' },
            { word: 'dosage', definition: 'amount of medicine to take' },
            { word: 'side effects', definition: 'unwanted effects from medicine' },
            { word: 'dizzy', definition: 'feeling like the room is spinning' },
            { word: 'fever', definition: 'higher than normal body temperature' },
            { word: 'infection', definition: 'illness caused by germs entering the body' },
          ],
        },
      ],
    },
    {
      id: 'grammar-tabs',
      type: 'grammar-tabs',
      title: 'Grammar focus: should and could',
      emoji: '📖',
      tabs: [
        {
          label: 'Should',
          rules: [
            'Use should for advice and recommendations.',
            'Positive: Subject + should + base verb.',
            'Negative: Subject + should not (shouldn\'t) + base verb.',
            'Question: Should + subject + base verb?',
          ],
          examples: [
            'You should see a GP if the fever is high.',
            'You should check the dosage before taking medicine.',
            'You should not go to work with a serious infection.',
            'Should I go to the ER now?',
          ],
          use: 'Use should when you want to give strong, practical advice.',
        },
        {
          label: 'Could',
          rules: [
            'Use could for polite requests.',
            'Use could for possibility.',
            'Question: Could + subject + base verb?',
            'Statement of possibility: Subject + could + base verb.',
          ],
          examples: [
            'Could you tell me where the ER is?',
            'Could I have a painkiller, please?',
            'The diagnosis could be wrong.',
            'This symptom could mean an infection.',
          ],
          use: 'Use could to sound polite, or to say something is possible but not certain.',
        },
      ],
      highlights: ['should', 'shouldn\'t', 'could', 'Could you...?', 'Could I...?', 'possibility'],
    },
    {
      id: 'picture-description',
      type: 'writing-task',
      title: 'Describe the healthcare picture',
      emoji: '🖼️',
      imageSrc: '/assets/healthcare-hospital/picture-description.png',
      prompt: 'Look at the picture and describe what is happening. Use at least 6 healthcare words and include one sentence with should and one sentence with could.',
      wordBank: ['patient', 'nurse', 'doctor', 'ER', 'stretcher', 'examination', 'blood test', 'X-ray', 'prescription', 'painkiller'],
      starter: 'In this picture, I can see...',
      modelAnswer: 'In this picture, I can see a patient and a nurse in a hospital. The patient looks weak, so he should rest and follow the prescription. The doctor could order a blood test and an X-ray to find the cause of the fever.',
    },
    {
      id: 'reading',
      type: 'dialogue-reading',
      title: 'Reading: At the hospital',
      emoji: '📘',
      imageSrc: '/assets/healthcare-hospital/reading.png',
      characters: [{ name: 'Narrator', colorClass: 'bg-blue-100 text-blue-900 ring-blue-200' }],
      lines: [
        { speaker: 'Narrator', text: 'Yesterday, I felt very dizzy and had a high fever, so I went to the ER.' },
        { speaker: 'Narrator', text: 'The nurse was very kind and took me to the examination room.' },
        { speaker: 'Narrator', text: 'Soon, the GP arrived.' },
        { speaker: 'Narrator', text: 'He said I should have a blood test to check for an infection.' },
        { speaker: 'Narrator', text: 'He also thought I could have a broken rib, so he sent me for an X-ray.' },
        { speaker: 'Narrator', text: 'Luckily, I did not need surgery.' },
        { speaker: 'Narrator', text: 'The doctor gave me a prescription for antibiotics and some painkillers.' },
        { speaker: 'Narrator', text: 'He said I should check the dosage carefully to avoid side effects.' },
        { speaker: 'Narrator', text: 'Now I am at home, and I hope to recover soon.' },
      ],
      questions: [
        { question: 'Why did the person go to the ER?', sampleAnswer: 'Because they felt dizzy and had a high fever.' },
        { question: 'What tests did the doctor order?', sampleAnswer: 'A blood test and an X-ray.' },
        { question: 'Did the patient need surgery?', sampleAnswer: 'No, the patient did not need surgery.' },
        { question: 'What medicine did the patient get?', sampleAnswer: 'Antibiotics and painkillers.' },
      ],
    },
    {
      id: 'speaking-questions',
      type: 'warm-up-questions',
      title: 'Speaking questions',
      emoji: '🗣️',
      images: [
        '/assets/healthcare-hospital/speaking-1.jpg',
        '/assets/healthcare-hospital/speaking-2.jpg',
        '/assets/healthcare-hospital/speaking-3.png',
      ],
      questions: [
        {
          question: 'When was the last time you visited a hospital or a GP? Why did you go?',
          hint: 'Mention symptoms, tests, or treatment.',
        },
        {
          question: 'Have you ever had an X-ray or a blood test? Was it scary?',
          hint: 'Explain your feelings and what happened.',
        },
        {
          question: 'Do you usually follow the doctor\'s prescription exactly, or do you sometimes forget the dosage?',
          hint: 'Give an example and your reason.',
        },
      ],
    },
    {
      id: 'exercise-fill-blanks',
      type: 'fill-gaps',
      title: 'Exercise 1: Fill in the blanks',
      emoji: '✍️',
      instruction: 'Complete each sentence with the correct healthcare word.',
      questions: [
        { sentence: 'After the car accident, the victim was rushed to the ___.', hint: 'Emergency room', answer: 'ER' },
        { sentence: 'The doctor wrote a ___ for some strong antibiotics.', hint: 'Doctor note for medicine', answer: 'prescription' },
        { sentence: 'You ___ see a ___ if your heart keeps beating too fast.', hint: 'Advice + doctor type', answer: 'should specialist' },
        { sentence: 'The ___ told me to stay in bed until the results are ready.', hint: 'Hospital professional', answer: 'nurse' },
        { sentence: 'I feel a bit ___; I think I need to sit down.', hint: 'Spinning feeling', answer: 'dizzy' },
      ],
    },
    {
      id: 'exercise-multiple-choice',
      type: 'quiz-select',
      title: 'Exercises 3-5: Advice and choices',
      emoji: '✅',
      instruction: 'Choose the best option to complete each sentence.',
      options: [
        'should',
        'should not',
        'could',
        'X-ray',
        'bandage',
        'examination',
        'be',
        'Could',
      ],
      questions: [
        { sentence: 'You ___ take your dosage exactly as the doctor said.', answer: 'should' },
        { sentence: 'If you have a high fever, you ___ go to work.', answer: 'should not' },
        { sentence: 'To check if your arm is broken, you need an ___.', answer: 'X-ray' },
        { sentence: 'If you have a deep cut, the nurse will apply a ___.', answer: 'bandage' },
        { sentence: 'A routine medical check is also called an ___.', answer: 'examination' },
        { sentence: 'The diagnosis could ___ wrong.', answer: 'be' },
        { sentence: '___ you tell me where the ER is?', answer: 'Could' },
      ],
    },
    {
      id: 'exercise-sentence-builder',
      type: 'sentence-builder',
      title: 'Exercise 5: Polite requests with could',
      emoji: '🧩',
      prompt: 'Build the polite sentence in correct order.',
      sentences: [
        {
          chunks: ['you', 'where the ER is', 'Could', 'tell me'],
          correctOrder: ['Could', 'you', 'tell me', 'where the ER is'],
        },
        {
          chunks: ['painkiller', 'I', 'a', 'Could', 'have', 'please'],
          correctOrder: ['Could', 'I', 'have', 'a', 'painkiller', 'please'],
        },
        {
          chunks: ['wrong', 'could be', 'The diagnosis'],
          correctOrder: ['The diagnosis', 'could be', 'wrong'],
        },
      ],
    },
    {
      id: 'exercise-categorization',
      type: 'wordlist',
      title: 'Exercise 8: Categorization word bank',
      emoji: '🗂️',
      words: ['Ward', 'Pharmacist', 'Syrup', 'Surgeon', 'ICU', 'Antibiotics', 'GP', 'OR', 'Painkillers'],
    },
    {
      id: 'exercise-dialogue-completion',
      type: 'fill-gaps',
      title: 'Exercise 12: Dialogue completion',
      emoji: '💬',
      instruction: 'Complete the dialogue with the correct word.',
      questions: [
        { sentence: 'Patient: Doctor, I have a high ___.', hint: 'symptom', answer: 'fever' },
        { sentence: 'Doctor: Okay, we should do a ___ test first.', hint: 'medical test', answer: 'blood' },
        { sentence: 'Patient: ___ I have some ___ for the pain now?', hint: 'modal + medicine', answer: 'Could painkiller' },
        { sentence: 'Doctor: Yes, I will write a ___ for you.', hint: 'doctor note', answer: 'prescription' },
      ],
    },
    {
      id: 'exercise-true-false',
      type: 'true-false-quiz',
      title: 'Exercise 15: True or False',
      emoji: '✔️',
      statements: [
        { statement: 'A stretcher is used to transport patients who cannot walk.', answer: true },
        { statement: 'Antibiotics are used to treat broken bones.', answer: false },
        { statement: 'You go to the Operating Room for a routine check-up.', answer: false },
        { statement: 'A radiologist looks at your X-rays.', answer: true },
      ],
    },
    {
      id: 'results',
      type: 'results-checklist',
      title: 'Check your progress',
      emoji: '✅',
      checklist: [
        'use B1 healthcare vocabulary confidently',
        'differentiate between should and could',
        'understand the hospital reading text',
        'answer speaking questions with detail',
        'complete grammar and vocabulary tasks',
      ],
    },
  ],
}

export default lesson
