import type { Lesson } from '../types/lesson'

const lesson: Lesson = {
  title: 'I love what I do',
  level: 'A1/A2',
  sections: [
    {
      id: 'hero',
      type: 'hero',
      title: 'Welcome to today’s lesson',
      emoji: '🦒',
      level: 'A1/A2',
      subtitle: 'Work, grammar, and job application writing in one interactive lesson.',
      imageSrc: '/assets/i-love-what-i-do/hero.jpg',
      goals: [
        'Revise Present Simple and Present Continuous in work context',
        'Learn how to write a short job application email',
        'Practise vocabulary to talk about work and jobs',
      ],
      words: [
        'company',
        'employee',
        'salary',
        'office',
        'customer',
        'employer',
        'task',
        'staff',
        'bonus',
        'boss',
      ],
      functionalLanguage: [
        'His salary is good.',
        'They get on well with other employees.',
        'Her boss is really friendly.',
        'This week we are doing online courses.',
        'I check my emails every day.',
      ],
    },
    {
      id: 'wordlist',
      type: 'wordlist',
      title: 'Core work vocabulary',
      emoji: '🧙‍♂️',
      words: ['company', 'employee', 'salary', 'office', 'customer', 'employer', 'task', 'staff', 'bonus', 'boss'],
    },
    {
      id: 'grammar-tabs',
      type: 'grammar-tabs',
      title: 'Present Simple vs Present Continuous',
      emoji: '✅',
      tabs: [
        {
          label: 'Present Continuous',
          rules: [
            'Positive: S + am/is/are + V-ing',
            'Negative: S + am/is/are + not + V-ing',
            'Question: Am/Is/Are + S + V-ing?',
          ],
          examples: [
            'I am checking my emails now.',
            'She is talking to a customer.',
            'They are doing online courses this week.',
          ],
        },
        {
          label: 'Present Simple',
          rules: [
            'Affirmative: S + V / V-s',
            'Negative: S + do/does + not + V',
            'Question: Do/Does + S + V?',
          ],
          examples: [
            'I check my emails every day.',
            'Her boss works in the office.',
            'They get bonuses every month.',
          ],
        },
      ],
      highlights: ['am/is/are', 'do/does', 'not', '-s / -es', 'V-ing'],
    },
    {
      id: 'warm-up',
      type: 'warm-up-questions',
      title: 'Warm-up questions',
      emoji: '💼',
      images: [
        '/assets/i-love-what-i-do/work-1.jpg',
        '/assets/i-love-what-i-do/work-2.jpg',
        '/assets/i-love-what-i-do/work-3.jpg',
        '/assets/i-love-what-i-do/work-4.jpg',
      ],
      questions: [
        {
          question: 'What do all these people have in common?',
          hint: 'They all have jobs and work responsibilities.',
        },
        { question: 'Where do they work?', hint: 'In offices, stores, hospitals, and other workplaces.' },
        { question: 'What are they doing at work?', hint: 'Helping customers, checking tasks, and working with teams.' },
      ],
    },
    {
      id: 'vocabulary-match',
      type: 'vocabulary-match',
      title: 'Match words and definitions',
      emoji: '✅',
      items: [
        { word: 'company', definition: 'a business that produces or sells something' },
        { word: 'employee', definition: 'a worker' },
        { word: 'salary', definition: 'a fixed sum of money given to someone for work' },
        { word: 'office', definition: 'a place where people work at desks' },
        { word: 'customer', definition: 'a person who uses particular services' },
        { word: 'employer', definition: 'a person or company who pays workers to do a job' },
        { word: 'task', definition: 'a job a worker needs to do' },
        { word: 'staff', definition: 'all people who work at a company' },
        { word: 'bonus', definition: 'extra money given to a worker for good work' },
        { word: 'boss', definition: 'a person who manages the workers' },
      ],
    },
    {
      id: 'listening',
      type: 'listening-task',
      title: 'Listening: Who is speaking?',
      emoji: '🎧',
      audioSrc: '/assets/i-love-what-i-do/listening-1.mp3',
      note: 'Add your audio file here later.',
      options: ['boss', 'employee', 'customer', 'employer', 'office worker'],
      speakers: [
        { id: 's1', label: 'Speaker 1', answer: 'employee' },
        { id: 's2', label: 'Speaker 2', answer: 'boss' },
        { id: 's3', label: 'Speaker 3', answer: 'customer' },
        { id: 's4', label: 'Speaker 4', answer: 'office worker' },
      ],
    },
    {
      id: 'ranking',
      type: 'ranking-task',
      title: 'What matters most at work?',
      emoji: '✅',
      prompt: 'Rank these from 1 (most important) to 6.',
      items: [
        'good salary',
        'friendly boss',
        'good relations with other staff',
        'flexible hours',
        'bonuses for work',
        'chance to develop a career',
      ],
    },
    {
      id: 'sentence-builder',
      type: 'sentence-builder',
      title: 'Build correct sentences',
      emoji: '🧙‍♂️',
      prompt: 'Build each sentence from chunks.',
      sentences: [
        { chunks: ['other employees', 'They', 'with', 'get on well'], correctOrder: ['They', 'get on well', 'with', 'other employees'] },
        { chunks: ['is really', 'Her boss', 'friendly'], correctOrder: ['Her boss', 'is really', 'friendly'] },
        { chunks: ['we are doing', 'online courses', 'This week'], correctOrder: ['This week', 'we are doing', 'online courses'] },
        { chunks: ['I check', 'my emails', 'every day'], correctOrder: ['I check', 'my emails', 'every day'] },
        { chunks: ['for my work', 'I receive', 'almost every month', 'good bonuses'], correctOrder: ['I receive', 'good bonuses', 'for my work', 'almost every month'] },
      ],
    },
    {
      id: 'company-match',
      type: 'company-match',
      title: 'Company matching',
      emoji: '💼',
      options: ['technology company', 'fashion brand', 'car company', 'sports brand', 'fast food company'],
      items: [
        { company: 'Google', logo: '/assets/i-love-what-i-do/company-1.png', answer: 'technology company' },
        { company: 'Apple', logo: '/assets/i-love-what-i-do/company-2.png', answer: 'technology company' },
        { company: 'Nike', logo: '/assets/i-love-what-i-do/company-3.png', answer: 'sports brand' },
        { company: 'Mercedes-Benz', logo: '/assets/i-love-what-i-do/company-4.png', answer: 'car company' },
        { company: 'McDonald’s', logo: '/assets/i-love-what-i-do/company-5.png', answer: 'fast food company' },
        { company: 'Hennes & Mauritz', logo: '/assets/i-love-what-i-do/company-6.png', answer: 'fashion brand' },
      ],
    },
    {
      id: 'true-false',
      type: 'true-false-quiz',
      title: 'True or False',
      emoji: '✅',
      statements: [
        { statement: 'A good salary is important for many workers.', answer: true },
        { statement: 'A boss is always a customer.', answer: false },
        { statement: 'Employees can work in an office.', answer: true },
        { statement: 'A bonus is extra money for good work.', answer: true },
        { statement: 'Staff means only one worker.', answer: false },
      ],
    },
    {
      id: 'grammar-practice',
      type: 'grammar-practice',
      title: 'Grammar practice',
      emoji: '🧙‍♂️',
      activityA: [
        { sentence: 'I check emails every day.', answer: 'Present Simple' },
        { sentence: 'She is talking to a customer now.', answer: 'Present Continuous' },
        { sentence: 'They work for a big company.', answer: 'Present Simple' },
        { sentence: 'We are doing online courses this week.', answer: 'Present Continuous' },
      ],
      activityB: [
        { sentence: 'She ___ (work) in an office every day.', answer: 'works' },
        { sentence: 'They ___ (do) online courses this week.', answer: 'are doing' },
        { sentence: 'I ___ (check) emails every morning.', answer: 'check' },
        { sentence: 'He ___ (talk) to his boss now.', answer: 'is talking' },
      ],
      activityC: [
        { sentence: 'Her boss [is / are] friendly.', options: ['is', 'are'], answer: 'is' },
        { sentence: 'They [get / gets] bonuses.', options: ['get', 'gets'], answer: 'get' },
        { sentence: 'This week we [do / are doing] online courses.', options: ['do', 'are doing'], answer: 'are doing' },
        { sentence: 'She [doesn’t / don’t] work from home.', options: ['doesn’t', 'don’t'], answer: 'doesn’t' },
      ],
    },
    {
      id: 'phrasebox',
      type: 'phrasebox',
      title: 'Phrasebox',
      emoji: '💼',
      options: [
        'He is our boss',
        'Have a break',
        'Get bonuses',
        'Work for a big company',
        'Share the same office',
        'Do the tasks',
      ],
      cards: [
        { image: '/assets/i-love-what-i-do/phrase-1.jpg', answer: 'He is our boss' },
        { image: '/assets/i-love-what-i-do/phrase-2.jpg', answer: 'Have a break' },
        { image: '/assets/i-love-what-i-do/phrase-3.jpg', answer: 'Get bonuses' },
        { image: '/assets/i-love-what-i-do/phrase-4.jpg', answer: 'Work for a big company' },
        { image: '/assets/i-love-what-i-do/phrase-5.jpg', answer: 'Share the same office' },
        { image: '/assets/i-love-what-i-do/phrase-6.jpg', answer: 'Do the tasks' },
      ],
    },
    {
      id: 'email-reading',
      type: 'email-reading',
      title: 'Job application email reading',
      emoji: '✍️',
      email: {
        subject: 'Application for a position at Tesla',
        body: [
          'Dear Mr Bred,',
          '',
          'I am writing to apply for the position at your company Tesla. I believe my skills make me a good candidate for this job. I am able to perform difficult and interesting tasks. I’m interested in a big salary and a chance to develop my career. I am friendly and usually communicate well with other employees. I always try to get on well with customers. I am very motivated by getting bonuses for my work. I can work at the office or from home. I have experience working for big companies. I look forward to your answer.',
        ],
        closing: ['Yours sincerely,', 'Monica Smith'],
      },
      questions: [
        { question: 'What is the purpose of Monica’s email?', sampleAnswer: 'To apply for a job position.' },
        { question: 'What company does she want to work at?', sampleAnswer: 'Tesla.' },
        { question: 'What is she interested in?', sampleAnswer: 'A good salary and career development.' },
        { question: 'What are her personal qualities?', sampleAnswer: 'She is friendly and communicates well.' },
        { question: 'What is she motivated by?', sampleAnswer: 'Getting bonuses for her work.' },
      ],
    },
    {
      id: 'writing-task',
      type: 'writing-task',
      title: 'Write your own application',
      emoji: '✍️',
      prompt: 'Complete the fields to generate your own job application email.',
    },
    {
      id: 'results',
      type: 'results-checklist',
      title: 'Lesson results',
      emoji: '✅',
      checklist: [
        'write a job application',
        'talk about people at work',
        'use Present Simple and Present Continuous',
      ],
    },
  ],
}

export default lesson
